apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: default
spec:
  selector:
    app: adminer
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
