apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalogue-db-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/data
    type: DirectoryOrCreate
