apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogue-db-pvc
spec:
  volumeName: catalogue-db-pv
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
