apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: default
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image:  adminer
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
          name: adminer