apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: default
spec:
  selector:
    app: voting
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
